# @package _global_

trainer:
  max_epochs: 1
  accelerator: cpu
  detect_anomaly: true

data:
  num_workers: 0
  pin_memory: False
  persistent_workers: False
  nr_episodes_train: 5
  nr_episodes_val: 5
  nr_episodes_test: 2
