defaults:
  - paths: default
  - hydra: default
  - data: 2d
  - options: null
  - _self_

seed: 42

model:
  latent_dimension: 32
  input_channel: 3
  base_filters: 64
  kernel_size: 5
  lr: 0.001

trainer:
  max_epochs: 100

task_name: 2d_ae
