defaults:
  - _self_
  - paths: default
  - hydra: default
  - options: null
  - experiment/cfno: null

seed: 42

data:
  data_dir: data/2D-control
  ra: 10000
  types: ["ppo", "random", "zero"]
  batch_size: 32
  horizon: 20
  shift: 20
  nr_episodes_train: 20
  nr_episodes_val: 20
  nr_episodes_test: 20
  # Data efficiency settings
  num_workers: 2
  pin_memory: False
  persistent_workers: True
  normalize: True

model:
  lr: 3e-3
  control_mask: False
  n_modes_width: 16
  n_modes_height: 16
  hidden_channels: 16
  in_channels: 3
  out_channels: 3
  lifting_channels: 16
  projection_channels: 16
  n_layers: 6

trainer:
  max_epochs: 75
  accelerator: auto
  detect_anomaly: false

task_name: 2d_cfno