defaults:
  - paths: default
  - hydra: default
  - data: 2d
  - options: null
  - _self_

seed: 42

model:
  dim: 2d # options: 2d, 3d
  loss: H1
  lr: 0.001
  weight_decay: 0.001
  n_modes_time: 16
  n_modes_space: 16
  hidden_channels: 32
  in_channels: 3
  out_channels: 3
  lifting_channels: 16
  projection_channels: 16
  n_layers: 6

trainer:
  max_epochs: 100
  accelerator: auto
  detect_anomaly: false

task_name: 2d_fno
