defaults:
  - paths: default
  - hydra: default
  - data: 2d
  - options: null
  - _self_

seed: 42

model:
  latent_dimension: 64
  input_channel: 3
  channels: [16, 32, 64]
  kernel_size: 5
  ae_ckpt: ${paths.model_dir}/2d_ae/ra${data.ra}.ckpt
  lambda_id: 1
  lambda_fwd: 1
  lambda_hid: 5
  lr_operator: 0.0001
  lr_autoencoder: 0.001

trainer:
  max_epochs: 100

task_name: 2d_lran
