defaults:
  - paths: default
  - hydra: default
  - _self_

seed: 42

data:
  data_dir: data/2D
  ra: 1000000
  batch_size: 32
  start: 200
  end: 500
  train_steps: 15
  test_steps: 100
  train_shift: 10
  test_shift: 50
  stride: 1
  downsample_factor: 1
  nr_episodes_train: null # this means all of them
  nr_episodes_val: null
  nr_episodes_test: null
  # Data efficiency settings
  num_workers: 2
  pin_memory: True
  persistent_workers: True
  pressure: False
  normalize: True

model:
  loss: "mse"
  latent_dimension: 64
  input_channel: 3
  base_filters: 64
  kernel_size: 5
  ae_ckpt: ${paths.model_dir}/2d_ae/ra${data.ra}.ckpt
  lambda_id: 1
  lambda_fwd: 1
  lambda_hid: 5
  lr_operator: 0.0001
  lr_autoencoder: 0.001

algo:
  epochs: 75

task_name: 2d_lran
