defaults:
  - _self_
  - paths: default
  - hydra: default
  - options: null

seed: 42

data:
  data_dir: ${paths.data_dir}/2D
  ra: 1000000
  batch_size: 32
  start: 200
  end: 600
  train_steps: 15
  test_steps: 100
  train_shift: 5
  test_shift: 50
  stride: 1
  train_downsample: 1
  test_downsample: 1
  nr_episodes_train: null
  nr_episodes_val: null
  nr_episodes_test: null
  # Data efficiency settings
  num_workers: 2
  pin_memory: False
  persistent_workers: True
  pressure: False
  normalize: True

model:
  loss: "mse"
  latent_dimension: 64
  input_channel: 3
  base_filters: 64
  kernel_size: 5
  ae_ckpt: ${paths.model_dir}/2d_ae/ra${data.ra}.ckpt
  lambda_id: 1
  lambda_fwd: 1
  lambda_hid: 5
  lr_operator: 0.0001
  lr_autoencoder: 0.001

trainer:
  max_epochs: 100

task_name: 2d_lran
