defaults:
  - paths: default
  - hydra: default
  - data: 2d
  - options: null
  - _self_
  - experiment/test: null

model: fno # fno or lran
seed: 0
checkpoint: ${paths.model_dir}/2d_${model}/ra${data.ra}-${seed}.ckpt

tags: 
  - test
task_name: 2d_test