defaults:
  - paths: default
  - hydra: default
  - data: 2d
  - options: null
  - _self_

seed: 42

data:
  train_steps: 15

model:
  lr: 0.0001
  features: [32, 64, 128]

trainer:
  max_epochs: 100
  accelerator: auto
  detect_anomaly: false

task_name: 2d_unet
