defaults:
  - _self_
  - paths: default
  - hydra: default
  - options: null

seed: 42

data:
  data_dir: ${paths.data_dir}/2D
  ra: 1000000
  batch_size: 32
  start: 200
  end: 600
  train_steps: 15
  test_steps: 100
  train_shift: 5
  test_shift: 50
  stride: 1
  train_downsample: 1
  test_downsample: 1
  nr_episodes_train: null
  nr_episodes_val: null
  nr_episodes_test: null
  # Data efficiency settings
  num_workers: 2
  pin_memory: False
  persistent_workers: True
  pressure: False
  normalize: True

model:
  lr: 0.0001
  features: [32, 64, 128]

trainer:
  max_epochs: 50
  accelerator: auto
  detect_anomaly: false

task_name: 2d_unet
