defaults:
  - paths: default
  - hydra: default
  - data: 3d
  - options: null
  - _self_
  - experiment/ae: null

seed: 42

model:
  version: v1
  input_size: [4, 48, 32, 48]
  latent_channels: 8
  channels: [16, 32, 32, 64, 64]
  pooling: [true, false, true, false, true]
  drop_rate: 0.1
  batch_norm: True
  kernel_size: 5
  latent_kernel_size: 3
  lr: 0.001

trainer:
  max_epochs: 100
  accelerator: auto
  detect_anomaly: false

tags:
  - train

task_name: 3d_ae
