defaults:
  - paths: default
  - hydra: default
  - data: 3d
  - options: null
  - _self_
  - experiment/fno: null

seed: 42

model:
  lr: 1e-3
  n_modes_width: 16
  n_modes_height: 8
  n_modes_depth: 16
  hidden_channels: 32
  in_channels: 4
  out_channels: 4
  lifting_channels: 16
  projection_channels: 16
  n_layers: 6

trainer:
  max_epochs: 100
  accelerator: auto
  detect_anomaly: false

tags:
  - train

task_name: 3d_fno
