defaults:
  - paths: default
  - hydra: default
  - data: 3d
  - options: null
  - _self_
  - experiment/fno: null

seed: 42

model:
  lr: 1e-3
  n_modes_xy: 16
  n_modes_z: 8
  channels: 16
  hidden_channels: 32
  in_channels: 4
  out_channels: 4
  n_layers: 6
  loss: h1

trainer:
  max_epochs: 100
  accelerator: auto
  detect_anomaly: false

tags:
  - train

task_name: 3d_fno
