defaults:
  - paths: default
  - hydra: default
  - data: 3d
  - options: null
  - _self_
  - experiment/lran: null

seed: 42

model:
  ae_ckpt: ${paths.model_dir}/3d_ae/ld/ra${data.ra}.ckpt
  input_size: [4, 48, 32, 48]
  latent_dimension: 1024
  lambda_id: 1
  lambda_fwd: 1
  lambda_hid: 5
  lr_operator: 0.0001
  lr_autoencoder: 0.001
  train_autoencoder: true

trainer:
  max_epochs: 500
  accelerator: auto
  detect_anomaly: false

tags:
  - train

task_name: 3d_lran
