defaults:
  - paths: default
  - hydra: default
  - data: 3d
  - options: null
  - _self_
  - experiment/test: null

model: lran # fno, lran, unet
seed: 0
checkpoint: ${paths.model_dir}/3d_${model}/ra${data.ra}-${seed}.ckpt

tags:
  - test
task_name: 3d_test
