defaults:
  - paths: default
  - hydra: default
  - data: 3d
  - options: null
  - _self_
  - experiment/unet: null

seed: 42

model:
  lr: 0.001
  features: [32, 64]

trainer:
  max_epochs: 100
  accelerator: auto
  detect_anomaly: false

tags:
  - train

task_name: 3d_unet
